### ISSUE TITLE
Crate does not compile on stable Rust < 1.36

### ISSUE THREAD

**Issue by jean-noelp** [SimonSapin/rust-typed-arena#31]
Hello,

It seems that your librairie does not compile anymore since the 1.6.0, and also, all dependencies does not compile anymore too! (like test-junit)

```
error[E0506]: cannot assign to `self.state` because it is borrowed

   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/typed-arena-1.6.0/src/lib.rs:461:33

    |

451 |                     ref mut inner_iter,

    |                     ------------------ borrow of `self.state` occurs here

...

461 |                                 self.state = IterMutState::ChunkListRest { index, inner_iter };

    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.state` occurs here


error[E0506]: cannot assign to `self.state` because it is borrowed

   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/typed-arena-1.6.0/src/lib.rs:467:33

    |

451 |                     ref mut inner_iter,

    |                     ------------------ borrow of `self.state` occurs here

...

467 |                                 self.state = IterMutState::ChunkListCurrent { iter };

    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.state` occurs here

```
We are using the **nightly-2019-03-06** rust version.

Do you confirm this error ?
Could you check your publication please ?
:/

**Comment by rodrimati1992** [comment]
Can confirm that I had the same error in the CI for one of my libraries,in [a job that uses Rust 1.34 ](https://travis-ci.org/rodrimati1992/abi_stable_crates/jobs/585043093#L829).

**Comment by brendanzab** [comment]
Yes, I've ran into this issue too, building on my pinned version of Rust, which used to build fine on Rust 1.32:

- https://github.com/yeslogic/ddl/pull/168
- https://travis-ci.com/yeslogic/ddl/jobs/235770008

**Comment by brendanzab** [comment]
The PR that introduced this regression seems to be #31. It'd be nice if this could be fixed, and a specific rust version be pinned in the `.travis.yml`!

**Comment by brendanzab** [comment]
After some time trying different versions, it seems like `1.36.0` works!

**Comment by fitzgen** [comment]
This crate hasn't made any promises about maintaining compatibility with specific rust versions, just that it will always compile on the stable channel.

I think it is reasonable to add a stronger stability guarantee, but doing so requires the CI changes mentioned above and backporting the code to work with older rust versions. If someone is willing to do those things, I would be happy to review the PR and be willing to start making those stronger versioning guarantees from then on out.

**Comment by brendanzab** [comment]
I don't think it's necessary to make a promise on this, but I _have_ found that just having a specific version in the .travis.yml is makes me consider whether or not I want to break backwards compatibility on a library, especially if there is an easier work around. :)

I might see if I can look at this today.

**Comment by brendanzab** [comment]
Posted a patch at #33! Hope this helps!

**Comment by jean-noelp** [comment]
Thank you, we'll check this patch!

**Comment by fitzgen** [comment]
Published 1.6.1

**Comment by brendanzab** [comment]
Thanks! Really appreciate your work on maintaining this! 👏
