### PR TITLE
Fix rustc version regression

### LINKED ISSUE #31: Crate does not compile on stable Rust < 1.36
Hello,

It seems that your librairie does not compile anymore since the 1.6.0, and also, all dependencies does not compile anymore too! (like test-junit)

```
error[E0506]: cannot assign to `self.state` because it is borrowed

   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/typed-arena-1.6.0/src/lib.rs:461:33

    |

451 |                     ref mut inner_iter,

    |                     ------------------ borrow of `self.state` occurs here

...

461 |                                 self.state = IterMutState::ChunkListRest { index, inner_iter };

    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.state` occurs here


error[E0506]: cannot assign to `self.state` because it is borrowed

   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/typed-arena-1.6.0/src/lib.rs:467:33

    |

451 |                     ref mut inner_iter,

    |                     ------------------ borrow of `self.state` occurs here

...

467 |                                 self.state = IterMutState::ChunkListCurrent { iter };

    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.state` occurs here

```
We are using the **nightly-2019-03-06** rust version.

Do you confirm this error ?
Could you check your publication please ?
:/

### PR DESCRIPTION
**Pull request by brendanzab**
This commit:

- Pins the rustc version to 1.32.0
- Rearranges the mutable iterator logic to pass older versions of the borrow checker (pre-1.36)

Fixes #31

### CODE REVIEW

**Comment by brendanzab** [comment]
I've pinned to 1.32 because its the most recent version that seems to work for me on https://github.com/yeslogic/ddl, but it might be compatible with earlier rustc versions too.
